// styles.js - CropIQ Styles
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#16a34a',
  },
  header: {
    backgroundColor: '#16a34a',
    padding: 16,
    paddingTop: 8,
    alignItems: 'center',
  },
  headerSlogan: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 2,
  },
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  currentLocationSection: {
    backgroundColor: '#16a34a',
    padding: 20,
    paddingBottom: 24,
  },
  locationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  locationInfo: {
    flex: 1,
  },
  currentLocationLabel: {
    fontSize: 14,
    color: '#d1fae5',
    marginBottom: 4,
  },
  currentLocationName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  currentLocationProvince: {
    fontSize: 14,
    color: '#d1fae5',
  },
  changeButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  changeButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  weatherSummaryCards: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  summaryIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 11,
    color: '#d1fae5',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  getCropRecommendationBox: {
    backgroundColor: '#f0fdf4',
    margin: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#86efac',
  },
  recommendationIcon: {
    width: 48,
    height: 48,
    backgroundColor: '#16a34a',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  recommendationIconText: {
    fontSize: 24,
  },
  recommendationContent: {
    marginBottom: 16,
  },
  recommendationTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#166534',
    marginBottom: 4,
  },
  recommendationSubtitle: {
    fontSize: 14,
    color: '#16a34a',
  },
  viewRecommendationsButton: {
    backgroundColor: '#16a34a',
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  viewRecommendationsButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  section: {
    padding: 16,
  },
  weatherHistoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  weatherHistoryTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111827',
  },
  periodSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
  },
  periodSelectorText: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  temperatureTrendsCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  trendDetails: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  trendItem: {
    alignItems: 'center',
  },
  trendLabel: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 4,
  },
  trendValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#16a34a',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#111827',
  },
  locationButton: {
    backgroundColor: '#16a34a',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  locationButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  weatherCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  weatherCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  weatherIcon: {
    fontSize: 24,
    marginRight: 8,
  },
  weatherTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  weatherValue: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#16a34a',
  },
  weatherDetails: {
    fontSize: 12,
    color: '#6b7280',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 16,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
  },
  locationList: {
    maxHeight: 400,
  },
  locationOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  selectedPeriodOption: {
    backgroundColor: '#f0fdf4',
  },
  locationName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  selectedPeriodText: {
    color: '#16a34a',
  },
  locationProvince: {
    fontSize: 14,
    color: '#6b7280',
  },
  noResultsContainer: {
    padding: 32,
    alignItems: 'center',
  },
  noResultsText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: 4,
  },
  noResultsSubtext: {
    fontSize: 14,
    color: '#9ca3af',
  },
  customLocationSection: {
    padding: 16,
    paddingBottom: 8,
    backgroundColor: '#fef3c7',
    borderRadius: 8,
    marginBottom: 0,
  },
  customLocationLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#92400e',
    marginBottom: 8,
  },
  customLocationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  customLocationInput: {
    flex: 1,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#ffffff',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#fbbf24',
  },
  searchCustomButton: {
    backgroundColor: '#16a34a',
    width: 40,
    height: 40,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchCustomButtonDisabled: {
    backgroundColor: '#9ca3af',
  },
  customLocationDivider: {
    height: 1,
    backgroundColor: '#e5e7eb',
    marginVertical: 8,
  },
  predefinedLocationsLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f9fafb',
  },
  closeButton: {
    backgroundColor: '#f3f4f6',
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  infoBox: {
    backgroundColor: '#dbeafe',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#93c5fd',
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e40af',
    marginBottom: 8,
  },
  infoText: {
    fontSize: 14,
    color: '#1e3a8a',
    marginBottom: 4,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    padding: 16,
    paddingBottom: 8,
  },
  cropRecommendationSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  locationLabel: {
    fontSize: 14,
    color: '#6b7280',
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  warningBox: {
    backgroundColor: '#fef3c7',
    padding: 20,
    margin: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fbbf24',
    alignItems: 'center',
  },
  warningText: {
    fontSize: 14,
    color: '#92400e',
    marginBottom: 12,
    textAlign: 'center',
  },
  warningButton: {
    backgroundColor: '#f59e0b',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  warningButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  cropCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  modernCropCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  cropCardSelected: {
    borderWidth: 2,
    borderColor: '#16a34a',
    backgroundColor: '#f0fdf4',
  },
  cropCardContent: {
    flexDirection: 'row',
    padding: 16,
  },
  cropImageContainer: {
    width: 80,
    height: 80,
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  cropEmoji: {
    fontSize: 40,
  },
  cropImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  cropMainInfo: {
    flex: 1,
  },
  cropHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  cropTitleContainer: {
    flex: 1,
  },
  modernCropName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 2,
  },
  cropCategory: {
    fontSize: 13,
    color: '#6b7280',
  },
  modernSuitabilityBadge: {
    alignItems: 'flex-end',
  },
  modernSuitabilityPercent: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#16a34a',
  },
  modernSuitabilityLabel: {
    fontSize: 11,
    color: '#16a34a',
    backgroundColor: '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 2,
  },
  cropShortDescription: {
    fontSize: 14,
    color: '#4b5563',
    marginBottom: 12,
    lineHeight: 20,
  },
  cropQuickStats: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 12,
  },
  quickStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  quickStatText: {
    fontSize: 12,
    color: '#6b7280',
  },
  viewDetailsButton: {
    backgroundColor: '#16a34a',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  viewDetailsButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  cropActionButtons: {
    flexDirection: 'row',
    marginTop: 8,
    gap: 8,
  },
  cropSelectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#16a34a',
    backgroundColor: '#ffffff',
    gap: 6,
  },
  cropSelectButtonSelected: {
    backgroundColor: '#16a34a',
    borderColor: '#16a34a',
  },
  cropSelectButtonText: {
    color: '#16a34a',
    fontSize: 14,
    fontWeight: '600',
  },
  cropSelectButtonTextSelected: {
    color: '#ffffff',
  },
  cropCardSelected: {
    borderWidth: 2,
    borderColor: '#16a34a',
    backgroundColor: '#f0fdf4',
  },
  cropDetailImageSection: {
    alignItems: 'center',
    marginBottom: 20,
    paddingVertical: 20,
    backgroundColor: '#f9fafb',
    borderRadius: 12,
  },
  cropDetailEmoji: {
    fontSize: 64,
    marginBottom: 12,
  },
  cropDetailImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    marginBottom: 12,
  },
  cropCategoryBadge: {
    backgroundColor: '#16a34a',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
  },
  cropCategoryText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  companionPlantsText: {
    fontSize: 15,
    color: '#111827',
    fontWeight: '500',
    marginBottom: 8,
  },
  companionPlantsNote: {
    fontSize: 13,
    color: '#6b7280',
    fontStyle: 'italic',
    lineHeight: 18,
  },
  cropHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  cropInfo: {
    flex: 1,
  },
  cropName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  cropDescription: {
    fontSize: 14,
    color: '#6b7280',
  },
  suitabilityBadge: {
    backgroundColor: '#dcfce7',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
  },
  suitabilityText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#16a34a',
  },
  cropTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  cropTag: {
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    fontSize: 12,
  },
  modalFull: {
    flex: 1,
    backgroundColor: '#fff',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#16a34a',
    padding: 16,
  },
  modalHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  closeIcon: {
    fontSize: 24,
    color: '#fff',
  },
  modalBody: {
    padding: 16,
  },
  cropDetailDescription: {
    fontSize: 16,
    color: '#6b7280',
    marginBottom: 20,
  },
  detailSection: {
    marginBottom: 24,
  },
  detailSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  detailLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  diseaseItem: {
    fontSize: 14,
    color: '#374151',
    marginBottom: 8,
  },
  managementText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  moduleCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  moduleIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  moduleContent: {
    marginBottom: 12,
  },
  moduleTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  moduleDescription: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  moduleDuration: {
    fontSize: 12,
    color: '#9ca3af',
  },
  moduleButton: {
    backgroundColor: '#8b5cf6',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  moduleButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  profileCard: {
    backgroundColor: '#fff',
    margin: 16,
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    backgroundColor: '#d1fae5',
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    overflow: 'hidden',
  },
  profileAvatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  profileAvatarText: {
    fontSize: 32,
  },
  editProfilePictureContainer: {
    width: 120,
    height: 120,
    backgroundColor: '#e5e7eb',
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: '#16a34a',
  },
  editProfilePictureImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  editProfilePictureEmoji: {
    fontSize: 48,
  },
  changeProfilePictureButton: {
    flexDirection: 'row',
    backgroundColor: '#16a34a',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    gap: 8,
  },
  changeProfilePictureText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  profileName: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  profileSubtitle: {
    fontSize: 14,
    color: '#6b7280',
  },
  profileSection: {
    marginBottom: 20,
  },
  profileField: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  profileFieldLabel: {
    fontSize: 14,
    color: '#6b7280',
  },
  profileFieldValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  editButton: {
    borderWidth: 1,
    borderColor: '#16a34a',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  editButtonText: {
    color: '#16a34a',
    fontWeight: '600',
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: -30,
  },
  navButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  navButtonActive: {
    backgroundColor: '#f0fdf4',
  },
  navLabel: {
    fontSize: 10,
    color: '#6b7280',
  },
  navLabelActive: {
    color: '#16a34a',
    fontWeight: '600',
  },
  loadingContainer: {
    padding: 32,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6b7280',
  },
  errorBox: {
    backgroundColor: '#fee2e2',
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fca5a5',
    alignItems: 'center',
    marginBottom: 16,
  },
  errorText: {
    fontSize: 14,
    color: '#991b1b',
    textAlign: 'center',
    marginBottom: 12,
  },
  retryButton: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  dataSourceText: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 12,
    fontStyle: 'italic',
  },
  
  
  // Login Page Styles
  loginSafeArea: {
    flex: 1,
    backgroundColor: '#16a34a',
  },
  loginContainer: {
    flex: 1,
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 40,
  },
  loginLogo: {
    width: 120,
    height: 120,
    marginBottom: 12,
    borderRadius: 5,
    overflow: 'hidden',
  },
  loginSubtitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 8,
  },
  loginDescription: {
    fontSize: 16,
    color: '#d1fae5',
    textAlign: 'center',
  },
  loginForm: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  loginErrorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  loginErrorText: {
    color: '#ef4444',
    fontSize: 14,
    marginLeft: 8,
    flex: 1,
  },
  loginInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  loginInputIcon: {
    marginRight: 12,
  },
  loginInput: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
  },
  loginPasswordToggle: {
    padding: 4,
  },
  loginForgotPassword: {
    alignSelf: 'flex-end',
    marginBottom: 24,
  },
  loginForgotPasswordText: {
    color: '#16a34a',
    fontSize: 14,
    fontWeight: '600',
  },
  loginButton: {
    backgroundColor: '#16a34a',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  loginDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  loginDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e5e7eb',
  },
  loginDividerText: {
    marginHorizontal: 16,
    color: '#9ca3af',
    fontSize: 14,
  },
  loginSignupLink: {
    alignItems: 'center',
  },
  loginSignupLinkText: {
    color: '#6b7280',
    fontSize: 14,
  },
  loginSignupLinkBold: {
    color: '#16a34a',
    fontWeight: '600',
  },
  // Crop Selection Page Styles
  cropSelectionSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  cropSelectionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginBottom: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cropSelectionCardSelected: {
    borderColor: '#16a34a',
    backgroundColor: '#f0fdf4',
  },
  cropSelectionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cropSelectionImageContainer: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  cropSelectionImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  cropSelectionEmoji: {
    fontSize: 30,
  },
  cropSelectionInfo: {
    flex: 1,
  },
  cropSelectionName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  cropSelectionCategory: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 4,
  },
  cropSelectionDescription: {
    fontSize: 13,
    color: '#4b5563',
    lineHeight: 18,
  },
  cropSelectionCheckbox: {
    marginLeft: 12,
  },


  plantingSignalCard: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: -16, // This makes it slightly overlap the green header, which looks modern
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: '#fff', // Default background
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
    alignItems: 'center',
  },
  plantingSignalIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  plantingSignalContent: {
    flex: 1,
  },
  plantingSignalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  plantingSignalMessage: {
    fontSize: 14,
    lineHeight: 20,
  },

  // Article Page Modern Styles
  articleHeader: {
    position: 'relative',
    height: 250,
    backgroundColor: '#16a34a',
  },
  articleHeaderImage: {
    width: '100%',
    height: '100%',
    opacity: 0.8,
  },
  articleHeaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
    padding: 20,
  },
  articleFloatingBack: {
    position: 'absolute',
    top: 40,
    left: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  articleTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    lineHeight: 34,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  articleMetaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  articleBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#16a34a',
  },
  articleBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  articleDuration: {
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '600',
  },
  articleBody: {
    backgroundColor: '#ffffff',
    marginTop: -20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 60,
  },
  articleParagraph: {
    fontSize: 17,
    lineHeight: 28,
    color: '#374151',
    marginBottom: 20,
    textAlign: 'left',
  },
  articleSectionHeader: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#111827',
    marginTop: 12,
    marginBottom: 16,
  },
  articleQuoteBox: {
    backgroundColor: '#f0fdf4',
    borderLeftWidth: 4,
    borderLeftColor: '#16a34a',
    padding: 20,
    marginVertical: 24,
    borderRadius: 8,
  },
  articleQuoteText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#166534',
    fontStyle: 'italic',
    fontWeight: '500',
  },
  articleImageCaption: {
    fontSize: 13,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 20,
    fontStyle: 'italic',
  },
  articleFooter: {
    marginTop: 20,
    paddingTop: 30,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  completeButton: {
    backgroundColor: '#16a34a',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#16a34a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  completeButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  completedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#d1fae5',
    padding: 20,
    borderRadius: 16,
    gap: 15,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  completedBannerText: {
    flex: 1,
    color: '#065f46',
    fontSize: 16,
    fontWeight: '700',
  },
  articleContentImage: {
    width: '100%',
    height: 220,
    borderRadius: 16,
    marginVertical: 10,
  },

  // ── Profile Redesign (DEMO) ───────────────────────────────────
  profileContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  profileMainHeader: {
    backgroundColor: '#16a34a',
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  profileHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  profileHeaderIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  profileHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  profileHeaderSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  profileContentScroll: {
    flex: 1,
    marginTop: -20,
    paddingHorizontal: 16,
  },
  profileSectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  profileSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  profileSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
  },
  profileSectionEditButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
  },
  profileSectionEditButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
  },
  profileLocationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileLocationIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileLocationLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 2,
  },
  profileLocationValue: {
    fontSize: 12,
    color: '#666666',
  },
  profileLocationSubvalue: {
    fontSize: 12,
    color: '#999999',
    marginTop: 2,
  },
  profileDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  profileDetailItemLast: {
    marginBottom: 0,
  },
  profileDetailIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileDetailLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 2,
  },
  profileDetailValue: {
    fontSize: 12,
    color: '#666666',
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileStatNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#16a34a',
    marginBottom: 4,
  },
  profileStatLabel: {
    fontSize: 11,
    color: '#666666',
    textAlign: 'center',
  },
  savedLocationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
  },
});

export default styles;